### PR TITLE
feat: allow config file to be defined via environment variable

### PR DESCRIPTION
**Pull request by abannachGrafana**
## Description

- add config file location fetching from environment variable (`CONFIG_PATH`). Defaulting to `config.json` (previous value) if environment variable is not defined.
- preserves backwards compatibility by not requiring `CONFIG_PATH` to be defined

### CODE REVIEW

**Review by dabeeeenster — APPROVED** [review]
LGTM

**Comment by dabeeeenster** [comment]
Couple of linting errors to fix!

**Comment by abannachGrafana** [comment]
@dabeeeenster I added some doc around getting pre-commit hooks setup locally in the contributing guide.

**Review by matthewelwell — APPROVED** [review]

**Comment by matthewelwell** [comment]
Thanks for this @abannachGrafana! I think we'll move the documentation you added in contributing.md but we'll do that in [this PR](https://github.com/Flagsmith/edge-proxy/pull/98) so I'm happy to merge this as it is.

**Pull request merged**
